# Hook to keep requirements.txt in sync with uv.lock
repos:
    - repo: https://github.com/astral-sh/uv-pre-commit
      # uv version.
      rev: 0.8.7
      hooks:
          - id: uv-export
            args:
                [
                    "--no-editable",
                    "--no-dev",
                    "--frozen",
                    "--output-file=requirements.txt",
                    "--quiet"
                ]
